import assert from 'node:assert/strict';import fs from 'node:fs';import {prepaidAudioDecision as d} from './prepaid-audio.mjs';
const s={product:'MAN',contentScope:'OFFICIAL_ONLY',reservedOfficialIdentity:true,reservedIdentityEvidenceSha256:'fixture-reservation-hash',standingAuthority:true,balanceVerified:true,balanceEvidenceRef:'fixture-private-balance',costEstimateEvidenceRef:'fixture-upper-bound',currency:'USD',prepaidUsd:1,unsettledUsd:.2,reservedUsd:.3,nextCostUpperBoundUsd:.4,hardControlsPermit:true};
assert.equal(d(s).code,'RESERVE_THEN_TARGETED_AUDIO');assert.equal(d({...s,exactAssetPass:true,bindingMatches:true,balanceVerified:false}).code,'REUSE_NO_PAID_CALL');assert.equal(d({...s,exactAssetPass:true,bindingMatches:false,balanceVerified:false}).code,'AUDIO_BUDGET_RECONCILIATION_REQUIRED');
for(const c of [{product:'B'},{contentScope:'PRIVATE_USER'},{reservedOfficialIdentity:false},{standingAuthority:false}])assert.equal(d({...s,...c}).code,'OUTSIDE_STANDING_AUDIO_AUTHORITY');
for(const c of [{providerOrBillingChange:true},{autoTopUp:true},{newBillingCommitment:true},{increaseBudget:true}])assert.equal(d({...s,...c}).code,'OWNER_DECISION_REQUIRED');
for(const c of [{balanceVerified:false},{prepaidUsd:null},{unsettledUsd:NaN},{reservedUsd:-1},{nextCostUpperBoundUsd:Infinity},{currency:'THB'}])assert.equal(d({...s,...c}).code,'AUDIO_BUDGET_RECONCILIATION_REQUIRED');
const noFunds=d({...s,nextCostUpperBoundUsd:.8});assert.equal(noFunds.code,'OWNER_FUNDING_REQUIRED');assert.equal(noFunds.minimumTopUpUsd,.3);assert.equal(noFunds.stopScope,'PAID_AUDIO_BRANCH_ONLY');assert.equal(noFunds.independentNonAudioContinues,true);assert.equal(d({...s,hardControlsPermit:false}).code,'AUDIO_EXECUTION_CONTROL_BLOCKED');
const t=JSON.parse(fs.readFileSync(new URL('./trigger-templates.v0.1.json',import.meta.url)));assert.deepEqual(t.lanes.map(x=>x.lane),['CURRICULUM_3','PRACTICE_2','OPERATIONS_4']);for(const l of t.lanes){assert.equal(l.event.params.only_on_merge,true);assert.equal(l.watchdog.enabled,false);}const authority=JSON.parse(fs.readFileSync(new URL('../../../docs/content-pipeline/registry/official-1000-production-authority.json',import.meta.url)));assert.equal(authority.audio_spend.per_lesson_batch_segment_reapproval,false);assert.equal(authority.audio_spend.auto_top_up,false);assert.equal(authority.scope.reserved_lesson_count,1000);
console.log('PASS: official scope, unchanged billing, exact reuse, conservative prepaid reservation, unknown-balance distinction, paid-only funding stop, portable inactive lane templates. No paid/API/product gates.');
