import assert from 'node:assert/strict';import {validate} from './practice-transition-merge.mjs';
const policy={repository:'bttdavid1948-sudo/my-dictation-app',repository_id:1377742729,scope:'OFFICIAL_MAN_1000_ONLY',lane:'PRACTICE_2',branch_prefix:'practice/passive-',allowed_destination_lanes:['OPERATIONS_4','PRACTICE_2','CURRICULUM_3','OWNER'],immutable_pipeline_fields:['contract_ref','contract_status','frozen_interface_ref','production_queue_enabled','preproduction_gates','preproduction_result','postproduction_gates','boundaries'],allowed_changed_files:['docs/content-pipeline/registry/pipeline.json','docs/content-pipeline/registry/artifacts.json','docs/content-pipeline/registry/batch-01-completion-checkpoint.json','docs/content-pipeline/registry/batch-01-readiness.json','docs/content-pipeline/registry/batch-01-autonomous-orchestration-readiness.json','docs/content-pipeline/registry/batch-02-watcher-pilot.json']};
const next={code:'PRODUCTION_READY_BATCH_02',responsible_lane:'OPERATIONS_4',requires:'x'},base={contract_ref:'c',contract_status:'FROZEN',frozen_interface_ref:'f',production_queue_enabled:false,preproduction_gates:['a'],preproduction_result:'r',postproduction_gates:['b'],boundaries:['x'],next_action:{code:'PRACTICE_PREPRODUCTION_BATCH_02',responsible_lane:'PRACTICE_2'}},cand={...base,next_action:next};
const lesson={lesson_id:'MAN-0001',unique_purpose_pass:true,curriculum_ready:true,practice_preprod_ready:true,contract_precheck_valid:true,production_ready:true,practice_conflict:'NONE',comprehension_operator:'CORE_COMPREHENSION',speech_operator:'TARGETED_DICTATION'};
const transition={scope:'OFFICIAL_MAN_1000_ONLY',owner_lane:'PRACTICE_2',production_queue_enabled:false,audio_created:false,operations_work_performed:false,status:'PASS',lessons:[lesson],gate_summary:{unique_purpose_pass:1,curriculum_ready:1,practice_preprod_ready:1,contract_precheck_valid:1,production_ready:1},final_practice_ready_claimed:false,produced_contract_valid_claimed:false,source_refs:['practice-production-spec@v0.1','curriculum-practice-contract@v0.3','content-pipeline-contract@v0.2'],next_action:next};
const old={id:'x',version:'v0.1',owner_lane:'X'},added={id:'batch-02-practice-preproduction',version:'v0.1',owner_lane:'PRACTICE_2',validation_status:'HASH_VERIFIED',practice_validation_status:'PRACTICE_VALIDATED',location:{store:'GitHub registry evidence'}};
const mirrors={};for(const p of policy.allowed_changed_files.slice(2)){if(p.includes('batch-01-')||p.includes('watcher-pilot'))mirrors[p]={next_action:next,__base:{next_action:base.next_action}};}
const input={policy,mainPipeline:base,candidatePipeline:cand,mainArtifacts:{artifacts:[old]},candidateArtifacts:{artifacts:[old,added]},transition,files:[{filename:'docs/content-pipeline/registry/pipeline.json'},{filename:'docs/content-pipeline/registry/artifacts.json'},{filename:'docs/content-pipeline/registry/batch-02-practice-preproduction.json'},...Object.keys(mirrors).map(filename=>({filename}))],pr:{head:{ref:'practice/passive-batch02-v0.1',sha:'h'},base:{ref:'main',repo:{full_name:policy.repository,id:policy.repository_id}},state:'open',draft:false,user:{login:'bttdavid1948-sudo'}},run:{head_sha:'h',conclusion:'success',event:'pull_request'},main:'m',candidateDocs:mirrors};
assert.equal(validate(input).decision,'PRACTICE_TRANSITION_ALLOWED');
const bad=structuredClone(input);bad.transition.lessons[0].practice_preprod_ready=false;assert.throws(()=>validate(bad));
console.log(JSON.stringify({status:'PASS',tests:'happy_path_and_fail_closed'}));
