import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import {validate} from './scoped-merge.mjs';
const policy=JSON.parse(fs.readFileSync(new URL('./scoped-merge-policy.v0.1.json',import.meta.url))),inputs=Object.fromEntries(policy.inputs.map(p=>[p,fs.readFileSync(p,'utf8')]));
// Replay the approved pre-probe state, including after current canonical advances.
const pipeline=JSON.parse(inputs[policy.inputs[0]]);pipeline.next_action={code:'BLOCKED_AUTOMATION_MERGE_AUTHORITY_PROPAGATION',responsible_lane:'OPERATIONS_4'};inputs[policy.inputs[0]]=JSON.stringify(pipeline);
const pilot=JSON.parse(inputs[policy.inputs[2]]);pilot.status='BLOCKED_AUTOMATION_MERGE_AUTHORITY_PROPAGATION';inputs[policy.inputs[2]]=JSON.stringify(pilot);
const repo={id:1377742729,full_name:policy.repository},main='a'.repeat(40),head='b'.repeat(40);
const receipt={schema_version:'1.0',probe_id:policy.probe_id,status:'VALIDATED_HARMLESS_RECEIPT',scope:policy.scope,responsible_lane:policy.lane,repository:policy.repository,source_main:main,canonical_next_action:{code:'BLOCKED_AUTOMATION_MERGE_AUTHORITY_PROPAGATION',responsible_lane:policy.lane},input_sha256:Object.fromEntries(policy.inputs.map(p=>[p,createHash('sha256').update(inputs[p]).digest('hex')])),batch01_complete_count:12,batch02_production_opened:false,paid_calls:0,semantic_dispositions_performed:false,passed_gates_rerun:false,policy_id:policy.policy_id,wake_pr:111,checked_at:'2026-10-05T07:00:00Z'};
const s={policy,inputs,receipt,main,pr:{state:'open',draft:false,number:112,user:{login:policy.author},base:{ref:'main',repo},head:{ref:policy.branch,sha:head,repo},changed_files:1},run:{id:1,head_sha:head,head_branch:policy.branch,event:'pull_request',status:'completed',conclusion:'success',path:policy.ci_workflow,repository:repo,head_repository:repo,pull_requests:[{number:112}]},files:[{filename:policy.receipt_path,status:'added',deletions:0}],commit:{parents:[{sha:main}]},receiptType:'file',receiptBytes:2000,receiptText:JSON.stringify(receipt),wake:{merged:true,merge_commit_sha:main,base:{ref:'main',repo}}};
assert.equal(validate(s).decision,'SCOPED_RECEIPT_MERGE_ALLOWED');
const mutations=[x=>x.pr.head.repo.id=5,x=>x.pr.head.ref='ops/watcher-arbitrary',x=>x.pr.user.login='attacker',x=>x.pr.base.ref='dev',x=>x.pr.draft=true,x=>x.run.conclusion='failure',x=>x.run.event='push',x=>x.run.path='other.yml',x=>x.run.head_sha='c'.repeat(40),x=>x.run.pull_requests=[],x=>x.pr.changed_files=2,x=>x.files.push({filename:'index.html'}),x=>x.files[0].filename='index.html',x=>x.files[0].status='modified',x=>x.commit.parents=[{sha:'c'.repeat(40)}],x=>x.receiptType='symlink',x=>x.receiptBytes=10000,x=>x.receipt.scope='PRODUCT_B',x=>x.receipt.responsible_lane='PRACTICE_2',x=>x.receipt.paid_calls=1,x=>x.receipt.batch02_production_opened=true,x=>x.receipt.semantic_dispositions_performed=true,x=>x.receipt.passed_gates_rerun=true,x=>x.receipt.source_main='c'.repeat(40),x=>x.receipt.input_sha256[policy.inputs[0]]='bad',x=>x.receipt.security_action='L5',x=>x.receipt.spending_authority='unlimited',x=>x.wake.merged=false,x=>x.wake.merge_commit_sha='c'.repeat(40),x=>x.receipt.checked_at='invalid',x=>x.policy.production_enabled=true,x=>x.policy.repository='other/repo',x=>x.inputs[policy.inputs[0]]=x.inputs[policy.inputs[0]].replace('"FROZEN"','"UNFROZEN"'),x=>x.inputs[policy.inputs[1]]=x.inputs[policy.inputs[1]].replace('"reserved_lesson_count": 1000','"reserved_lesson_count": 2000')];
for(const change of mutations){const x=structuredClone(s);change(x);assert.throws(()=>validate(x));}
console.log(`PASS: one receipt-only fixture and ${mutations.length} fail-closed adversarial cases; no external calls or product gate rerun.`);
