import assert from 'node:assert/strict';import fs from 'node:fs';import {resolveLesson,operationKey,reconcileReceipt,planIndependent,actualBatch01} from './resolve.mjs';
const ready={lessonId:'FIXTURE-ONLY',lessonVersion:'v0.1',realizationId:'FIXTURE-AUDIO-v0.1',uniquePurposePass:true,curriculumReady:true,practicePreprodReady:true,contractPrecheck:'PASS',assetsBound:true,ordinaryAudioQa:'PASS',finalPracticeReady:'PASS',contractValid:'PASS',supportReady:true,rightsReady:true,releaseAuthorized:true,releaseDeployed:true,desktopLive:true,mobileLive:true,feedbackWriteAck:true,rollbackVerified:true};
assert.equal(resolveLesson(ready).code,'COMPLETE');assert.equal(resolveLesson({...ready,accentUncertain:true}).code,'COMPLETE');assert.equal(resolveLesson({...ready,bindingMismatch:true}).code,'ASSET_BINDING_MISMATCH');assert.equal(resolveLesson({...ready,concreteAudioDefect:'CUT_OFF'}).code,'TARGETED_VERSIONED_REWORK');
assert.equal(resolveLesson({...ready,uniquePurpose:'DUPLICATE'}).responsibleLane,'CURRICULUM_3');assert.equal(resolveLesson({...ready,practiceConflict:true}).responsibleLane,'PRACTICE_2');assert.equal(resolveLesson({...ready,finalPracticeReady:false}).code,'FINAL_EXACT_REALIZATION_DISPOSITION');assert.equal(resolveLesson({...ready,frozenContractBreaking:true}).code,'OWNER_DECISION_REQUIRED');assert.equal(resolveLesson({...ready,releaseAuthorized:false}).code,'OWNER_PERMISSION_REQUIRED');
assert.equal(resolveLesson({...ready,sameMethodFailures:2,newMethodAvailable:false}).code,'RETRY_ESCALATION');assert.equal(resolveLesson({...ready,sameMethodFailures:2,newMethodAvailable:true}).code,'RETRY_ESCALATION');assert.equal(resolveLesson({...ready,sameMethodFailures:2,methodChanged:true}).code,'COMPLETE');assert.equal(resolveLesson({...ready,capabilitiesExhausted:true}).code,'BLOCKED');
assert.equal(resolveLesson({...ready,releaseDeployed:false}).code,'CONTROLLED_RELEASE');assert.equal(resolveLesson({...ready,mobileLive:false}).code,'MINIMUM_LIVE_VERIFICATION');
const p={lessonId:'FIXTURE-ONLY',lessonVersion:'v0.1',realizationId:'FIXTURE-AUDIO-v0.1'},a={inputSha256:'canonical-hash',sha256:'immutable-hash'};const receipt={key:operationKey(p,'UPLOAD',a.sha256),inputSha256:a.inputSha256,outputSha256:a.sha256,status:'PASS'};
assert.equal(reconcileReceipt(p,'UPLOAD',a,receipt).action,'REUSE');assert.equal(reconcileReceipt({...p,realizationId:'v0.2'},'UPLOAD',a,receipt).code,'RECEIPT_BINDING_MISMATCH');assert.equal(reconcileReceipt(p,'UPLOAD',{...a,inputSha256:'changed-canonical'},receipt).code,'RECEIPT_BINDING_MISMATCH');assert.equal(reconcileReceipt(p,'UPLOAD',a,null).action,'MISSING');assert.equal(reconcileReceipt(p,'UPLOAD',a,{...receipt,status:'PARTIAL'}).action,'INCOMPLETE');
const independent=planIndependent([{...ready,finalPracticeReady:false},{...ready,lessonId:'SECOND-FIXTURE',releaseDeployed:false},ready]);assert.equal(independent.globalStop,false);assert.equal(independent.actionable.length,1);assert.equal(independent.handoffs.length,1);assert.equal(independent.completed.length,1);
const actual=actualBatch01();assert.equal(actual.completed.length,12);assert.equal(actual.actionable.length,0);assert.equal(actual.handoffs.length,0);assert.equal(actual.externalCalls,0);assert.equal(actual.newProductionStarted,false);
const receipts=JSON.parse(fs.readFileSync(new URL('./batch01-asset-receipts.json',import.meta.url),'utf8')).receipts;assert.equal(receipts.length,63);for(const r of receipts){assert.equal(reconcileReceipt({lessonId:r.lesson_id,lessonVersion:r.lesson_asset_version,realizationId:r.realization_id},'UPLOAD',{inputSha256:r.inputSha256,sha256:r.outputSha256},r).action,'REUSE');}
console.log('PASS:12 actual trace completions; exact receipt reuse and changed binding; partial resume; independent branch progression; Practice/Curriculum/Owner routes; retry escalation; accent uncertainty nonblocking. No product gate rerun.');
