import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {operationKey} from '../../../orchestration/resolve.mjs';
const [preparedDir,preproductionFile,sourceMain,outputFile]=process.argv.slice(2);
assert.ok(/^[a-f0-9]{40}$/.test(sourceMain));
const hash=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const manifest=read(path.join(preparedDir,'manifest.json'));
for(const [rel,v] of Object.entries(manifest)){const f=path.resolve(preparedDir,rel);assert.ok(f.startsWith(path.resolve(preparedDir)+path.sep));const b=fs.readFileSync(f);assert.equal(hash(b),v.sha256);assert.equal(b.length,v.size_bytes);}
const pre=read(preproductionFile);const packageNames=Object.keys(manifest).filter(x=>/^MAN-Batch-\d+-Prepared-Lesson-Assets-v[\d.]+\.json$/.test(x));assert.equal(packageNames.length,1);
const assetPath=path.join(preparedDir,packageNames[0]),body=fs.readFileSync(assetPath),pkg=JSON.parse(body);
assert.equal(pkg.scope,'OFFICIAL_MAN_1000_ONLY');assert.ok(/^[a-f0-9]{40}$/.test(pkg.source_main));assert.equal(pre.scope,pkg.scope);assert.ok(/^BATCH_\d+$/.test(pre.batch_id));assert.ok(pkg.assets.every(a=>a.batch_id===pre.batch_id));
const approved=new Map(pre.lessons.map(x=>[x.lesson_id,x]));assert.equal(pkg.assets.length,approved.size);
const authored=read(path.join(preparedDir,'materialization-source.json'));assert.equal(authored.length,pkg.assets.length);
const rows=pkg.assets.map(a=>{const p=approved.get(a.lesson_id),draft=authored.find(x=>x.id===a.lesson_id);assert.ok(p&&draft);assert.ok(['unique_purpose_pass','curriculum_ready','practice_preprod_ready','contract_precheck_valid','production_ready'].every(k=>p[k]===true));
 assert.equal(a.canonical_transcript,draft.segments.map(x=>x[1]).join('\n'));assert.equal(a.title,draft.title);assert.equal(a.rights_qa,'ORIGINAL_AUTHORED_NO_EXTERNAL_MEDIA');
 const supportPath=path.join(preparedDir,'support',a.lesson_id+'-vi-VN-v0.1.json'),support=read(supportPath);assert.equal(support.lesson_id,a.lesson_id);assert.equal(support.canonical_lesson_asset_version,a.lesson_asset_version);assert.equal(support.support_locale,'vi-VN');assert.equal(support.segments.length,a.segments.length);assert.equal(new Set(support.segments.map(x=>x.segment_id)).size,a.segments.length);
 for(const s of a.segments)assert.ok(support.segments.find(x=>x.segment_id===s.segment_id)?.translation?.trim());
 return {lesson_id:a.lesson_id,lesson_asset_version:a.lesson_asset_version,key:operationKey({lessonId:a.lesson_id,lessonVersion:a.lesson_asset_version},'ORIGINAL_RIGHTS_REVIEW',hash(body)),rights_ready:true,source_type:'OPERATIONS_ORIGINAL_AUTHORED',rights_basis:'Exact transcript/title matches preserved original Operations authored preparation; no third-party text/media or license imported. Audio provenance remains a separate gate.',support_structural_valid:true,support_qa_status:'LINGUISTIC_QA_PENDING',support_bundle_sha256:hash(fs.readFileSync(supportPath)),publication_allowed:false};
});
const identity=hash(body);if(fs.existsSync(outputFile)){const old=read(outputFile);assert.equal(old.prepared_package_sha256,identity);assert.deepEqual(old.lesson_results,rows);console.log('REUSE_ORIGINAL_RIGHTS_RECEIPT');process.exit(0);}
const result={schema_version:'1.0',artifact_id:pre.batch_id.toLowerCase().replace('_','-')+'-original-rights-preparation',version:'v0.1',scope:pkg.scope,batch_id:pre.batch_id,owner_lane:'OPERATIONS_4',execution_context:'SINGLE_PRODUCTION_ORCHESTRATOR',procedure:'man-production-control',classification:'ROUTINE_EXECUTION',source_main:sourceMain,source_prepared_main:pkg.source_main,status:'ORIGINAL_CONTENT_RIGHTS_RECORDED_SUPPORT_STRUCTURE_CHECKED',prepared_package_sha256:identity,source_draft_sha256:hash(fs.readFileSync(path.join(preparedDir,'materialization-source.json'))),preproduction_sha256:hash(fs.readFileSync(preproductionFile)),lesson_results:rows,rights_ready_count:rows.length,support_structural_valid_count:rows.length,support_linguistic_qa_pass_count:0,actual_audio_created:false,PRACTICE_READY_claimed:false,CONTRACT_VALID_claimed:false,production_queue_opened:false,passed_gates_rerun:false,paid_calls:0,checked_at:new Date().toISOString()};
fs.mkdirSync(path.dirname(outputFile),{recursive:true});fs.writeFileSync(outputFile,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,rights_ready_count:rows.length,real_batch_operation:true,paid_calls:0}));
