import {chromium,devices} from '../mobile-release-runner/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {resolve,extname} from 'node:path';
const mode=process.env.MAN_EXECUTION_MODE||'desktop',live=process.env.MAN_VERIFY_TARGET==='live';
const out=new URL(`./evidence/${mode}/`,import.meta.url);await mkdir(out,{recursive:true});
const expected=JSON.parse(await readFile(new URL('../assets/official-lessons-man0844.json',import.meta.url),'utf8')).lessons[0];
const evidence={lessonId:'MAN-0844',lessonVersion:'v0.1',realizationId:'MAN-0844-MIXED-v0.1',target:live?'LIVE':'LOCAL_STAGING',mode,physicalDeviceClaim:false,startedAt:new Date().toISOString(),assets:[],layout:[]};
let server,browser,page;
const root=resolve(new URL('../',import.meta.url).pathname);
if(!live){server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=resolve(root,'.'+pathname+(pathname.endsWith('/')?'index.html':''));if(!p.startsWith(root+'/'))throw Error('path');const b=await readFile(p);res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.html':'text/html','.wav':'audio/wav','.png':'image/png'})[extname(p)]||'application/octet-stream');res.end(b);}catch(_){res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));}
const base=live?'https://bttdavid1948-sudo.github.io/my-dictation-app/':`http://127.0.0.1:${server.address().port}/`;
try{
  browser=await chromium.launch({headless:true});const context=await browser.newContext(mode==='mobile'?devices['Pixel 5']:{viewport:{width:1440,height:1000}});page=await context.newPage();
  evidence.browser=browser.version();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.manVerificationWebSpeech=0;if(window.speechSynthesis){const original=window.speechSynthesis.speak.bind(window.speechSynthesis);window.speechSynthesis.speak=(...args)=>{window.manVerificationWebSpeech++;return original(...args);};}});
  if(live){let available=false;for(let i=0;i<18;i++){const p=await context.request.get(new URL('assets/official-lessons-man0844.json',base).href);if(p.ok()){const d=await p.json();if(d.lessons.some(x=>x.audioRealizationRef===expected.audioRealizationRef)){available=true;break;}}await new Promise(r=>setTimeout(r,10000));}assert.ok(available,'Exact Pages catalog not deployed');}
  const catalog=await context.request.get(new URL('assets/official-lessons-man0844.json',base).href);assert.ok(catalog.ok());assert.deepEqual((await catalog.json()).lessons[0],expected);
  for(const audio of [expected.fullPanelAudio,...expected.items.map(x=>x.audio)]){const r=await context.request.get(new URL(audio.url,base).href);assert.ok(r.ok());const b=await r.body();assert.equal(createHash('sha256').update(b).digest('hex'),audio.sha256);evidence.assets.push({url:audio.url,sha256:audio.sha256,bytes:b.length});}
  await page.goto(base,{waitUntil:'domcontentloaded'});
  async function click(locator,label){await locator.scrollIntoViewIfNeeded();const d=await locator.evaluate(el=>{const r=el.getBoundingClientRect(),top=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {width:r.width,height:r.height,unobstructed:!!top&&(top===el||el.contains(top)),documentWidth:document.documentElement.scrollWidth,viewportWidth:innerWidth};});assert.ok(d.unobstructed,label+' obstructed');assert.ok(d.documentWidth<=d.viewportWidth+2,label+' overflow');evidence.layout.push({label,...d});if(mode==='mobile')await locator.tap();else await locator.click();}
  async function start(){const nav=page.getByRole('button',{name:'Kho bài học',exact:true}).filter({visible:true});await click(nav,'catalog nav');await click(page.getByRole('button',{name:'Xem tất cả bài học →',exact:true}).filter({visible:true}),'open library');const article=page.locator('#x-lib-grid article').filter({has:page.getByRole('heading',{name:expected.unitName,exact:true})});await article.waitFor({state:'visible'});await click(article.getByRole('button',{name:'🔥 Chiến bài này',exact:true}),'start exact pair');await page.locator('#man-panel-play').waitFor({state:'visible'});}
  async function ended(){await page.waitForFunction(()=>{const a=document.querySelector('#man-fixed-audio-player');return a&&(a.error||a.ended);},null,{timeout:60000});const a=await page.locator('#man-fixed-audio-player').evaluate(a=>({url:a.currentSrc,duration:a.duration,ended:a.ended,error:a.error?.code||null,dataset:{...a.dataset}}));assert.equal(a.error,null);assert.equal(a.ended,true);assert.equal(a.dataset.realizationId,expected.audioRealizationRef);return a;}
  await start();assert.equal(await page.locator('#man-panel-answer').count(),0,'Answer exposed before full pass');
  await click(page.locator('#man-panel-play'),'full panel first pass');
  evidence.fullPanel=await ended();assert.equal(evidence.fullPanel.dataset.segmentId,'FULL_PANEL');assert.equal(evidence.fullPanel.dataset.assetSha256,expected.fullPanelAudio.sha256);assert.ok(Math.abs(evidence.fullPanel.duration-expected.fullPanelAudio.durationSeconds)<0.01);
  await page.locator('#man-panel-submit').waitFor();
  await page.screenshot({path:new URL('panel.png',out).pathname,fullPage:true});
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('#man-panel-submit').waitFor();evidence.resume='PASS_EXACT_PANEL_AND_FULL_ENDED_RETAINED';
  for(const item of expected.items){await click(page.locator('#man-panel-replay-'+item.segmentId),'context '+item.segmentId);const actual=await ended();assert.equal(actual.dataset.segmentId,item.segmentId);assert.equal(actual.dataset.assetSha256,item.audio.sha256);assert.equal(actual.url,new URL(item.audio.url,base).href);evidence.assets.find(x=>x.sha256===item.audio.sha256).playback=actual;}
  await click(page.locator('#man-panel-report'),'full panel audio report');evidence.feedbackContext=JSON.parse(await page.locator('#x-audio-report-modal').getAttribute('data-audio-context'));assert.equal(evidence.feedbackContext.lessonId,'MAN-0844');assert.equal(evidence.feedbackContext.segmentId,'FULL_PANEL');assert.equal(evidence.feedbackContext.assetSha256,expected.fullPanelAudio.sha256);assert.equal(evidence.feedbackContext.realizationId,expected.audioRealizationRef);
  await page.locator('#x-audio-report-category').selectOption({label:'Vấn đề khác'});await page.locator('#x-audio-report-note').fill(`OPERATIONS_${mode.toUpperCase()}_SMOKE_TEST: exact MAN-0844 release verification, not a learner defect.`);
  if(live){await click(page.locator('#x-audio-report-send'),'feedback backend write');await page.locator('#x-audio-report-status').filter({hasText:'Đã gửi.'}).waitFor({timeout:45000});const id=await page.locator('#x-audio-report-status').getAttribute('data-report-id');assert.ok(id);evidence.feedbackDocumentIdSha256=createHash('sha256').update(id).digest('hex');evidence.feedbackWrite='ACKNOWLEDGED_BY_BACKEND';await page.screenshot({path:new URL('feedback.png',out).pathname,fullPage:true});}else evidence.feedbackWrite='NOT_SENT_STAGING';
  await click(page.locator('#x-audio-report-modal').getByRole('button',{name:'Đóng',exact:true}),'close feedback');
  await page.locator('input[name="panel-answer"][value="0"]').check();await click(page.locator('#man-panel-submit'),'submit comprehension');await page.locator('#man-panel-result').waitFor();
  evidence.comprehension=await page.evaluate(()=>ManMixedPanel.evidence());assert.equal(evidence.comprehension.correct,true);assert.equal(evidence.comprehension.responseAssisted,true);assert.equal(evidence.comprehension.contextReplays,6);assert.ok(evidence.comprehension.events.some(e=>e.kind==='COMPREHENSION_RESPONSE'&&e.evidence==='ASSISTED'));assert.equal(evidence.comprehension.overlapMastery,undefined);
  await page.screenshot({path:new URL('completion.png',out).pathname,fullPage:true});
  await click(page.locator('#man-panel-dictation'),'optional dictation');
  for(let i=0;i<expected.items.length;i++){await page.locator('#progress-tag').filter({hasText:`Câu ${i+1}/6`}).waitFor();await page.locator('#user-input').fill(expected.items[i].en);}
  await page.locator('#summary-section').getByRole('heading',{name:'Bạn vừa làm được gì?',exact:true}).waitFor({timeout:45000});evidence.dictationCompletion='6_OF_6_SEPARATE_FROM_COMPREHENSION';
  await start();await click(page.locator('#man-panel-play'),'independent negative pass');await ended();await page.locator('input[name="panel-answer"][value="1"]').check();await click(page.locator('#man-panel-submit'),'incorrect comprehension response');const negative=await page.evaluate(()=>ManMixedPanel.evidence());assert.equal(negative.correct,false);assert.equal(negative.responseAssisted,false);evidence.negativeComprehension='INCORRECT_NOT_100_PERCENT';
  evidence.pageErrors=errors;evidence.webSpeechRequests=await page.evaluate(()=>window.manVerificationWebSpeech);assert.deepEqual(errors,[]);assert.equal(evidence.webSpeechRequests,0,'Silent browser voice substitution');
  // Preview rollback in an isolated browser request route; production is unchanged.
  await context.route('**/assets/official-lessons-man0844.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({catalogVersion:1,publisher:'man',lessons:[]})}));
  await page.reload({waitUntil:'domcontentloaded'});await click(page.getByRole('button',{name:'Kho bài học',exact:true}).filter({visible:true}),'rollback catalog nav');
  await page.locator('article').filter({hasText:'MAN-0065'}).first().waitFor();assert.equal(await page.locator('article').filter({hasText:expected.unitName}).count(),0);assert.equal(await page.locator('#man-mixed-panel').count(),0);evidence.rollback='EMPTY_SCOPED_CATALOG_REMOVES_MAN0844_RETAINS_PRIOR_LESSONS';
  evidence.status='PASS';
}catch(e){evidence.status='FAIL';evidence.failure=String(e.stack||e);await page?.screenshot({path:new URL('failure.png',out).pathname,fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{evidence.finishedAt=new Date().toISOString();await writeFile(new URL('evidence.json',out),JSON.stringify(evidence,null,2));console.log(JSON.stringify({status:evidence.status,mode,target:evidence.target,failure:evidence.failure}));await browser?.close();server?.close();}
