import {chromium,devices} from '../mobile-release-runner/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {readFile,mkdir,writeFile} from 'node:fs/promises';import {createServer} from 'node:http';import {resolve,extname} from 'node:path';
const mode=process.env.MAN_EXECUTION_MODE||'desktop',live=process.env.MAN_VERIFY_TARGET==='live',id=process.env.MAN_LESSON_ID;
assert.ok(/^MAN-\d{4}$/.test(id));
const out=new URL(`./evidence/${id}/${mode}/`,import.meta.url);await mkdir(out,{recursive:true});
const expected=JSON.parse(await readFile(new URL('../assets/official-lessons-batch02.json',import.meta.url),'utf8')).lessons.find(x=>x.id===id);
const evidence={lessonId:id,lessonVersion:'v0.1',realizationId:expected.audioRealizationRef,target:live?'LIVE':'LOCAL_STAGING',mode,physicalDeviceClaim:false,startedAt:new Date().toISOString(),assets:[],layout:[]};
let server,browser,page;const root=resolve(new URL('../',import.meta.url).pathname);
if(!live){server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),p=resolve(root,'.'+pathname+(pathname.endsWith('/')?'index.html':''));if(!p.startsWith(root+'/'))throw Error('path');const b=await readFile(p);res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.html':'text/html','.wav':'audio/wav','.png':'image/png'})[extname(p)]||'application/octet-stream');res.end(b);}catch(_){res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));}
const base=live?'https://bttdavid1948-sudo.github.io/my-dictation-app/':`http://127.0.0.1:${server.address().port}/`;
try{
 browser=await chromium.launch({headless:true});const context=await browser.newContext(mode==='mobile'?devices['Pixel 5']:{viewport:{width:1440,height:1000}});page=await context.newPage();evidence.browser=browser.version();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.manVerificationWebSpeech=0;if(window.speechSynthesis){const orig=window.speechSynthesis.speak.bind(window.speechSynthesis);window.speechSynthesis.speak=(...args)=>{window.manVerificationWebSpeech++;return orig(...args);};}});
 if(live){let available=false;for(let i=0;i<18;i++){const r=await context.request.get(new URL('assets/official-lessons-batch02.json',base).href);if(r.ok()){const c=await r.json();if(c.lessons.some(x=>x.audioRealizationRef===expected.audioRealizationRef)){available=true;break;}}await new Promise(r=>setTimeout(r,10000));}assert.ok(available,'Exact Pages catalog not deployed');}
 const catalogResponse=await context.request.get(new URL('assets/official-lessons-batch02.json',base).href);assert.ok(catalogResponse.ok());const catalog=await catalogResponse.json();assert.deepEqual(catalog.lessons.find(x=>x.id===id),expected);
 for(const item of expected.fullPanelAudio?[...expected.items,{segmentId:'FULL_PANEL',audio:expected.fullPanelAudio}]:expected.items){const r=await context.request.get(new URL(item.audio.url,base).href);assert.ok(r.ok());const b=await r.body();assert.equal(createHash('sha256').update(b).digest('hex'),item.audio.sha256);evidence.assets.push({segmentId:item.segmentId,url:item.audio.url,sha256:item.audio.sha256,bytes:b.length});}
 const supportResponse=await context.request.get(new URL(expected.supportRef,base).href);assert.ok(supportResponse.ok());const support=await supportResponse.json();assert.equal(support.coverage,'FULL');assert.deepEqual(support.segments.map(s=>s.translation),expected.items.map(i=>i.vi));evidence.support='FULL_EXACT_SEGMENT_ALIGNMENT';
 await page.goto(base,{waitUntil:'domcontentloaded'});
 async function click(locator,label){await locator.evaluate(el=>el.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'}));const d=await locator.evaluate(el=>{const r=el.getBoundingClientRect(),top=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {width:r.width,height:r.height,unobstructed:!!top&&(top===el||el.contains(top)),documentWidth:document.documentElement.scrollWidth,viewportWidth:innerWidth};});assert.ok(d.unobstructed,label+' obstructed');assert.ok(d.documentWidth<=d.viewportWidth+2,label+' overflow');evidence.layout.push({label,...d});if(mode==='mobile')await locator.tap();else await locator.click();}
 async function start(){await click(page.getByRole('button',{name:'Kho bài học',exact:true}).filter({visible:true}),'catalog nav');await click(page.getByRole('button',{name:'Xem tất cả bài học →',exact:true}).filter({visible:true}),'open library');await page.locator('#x-lib-q').fill(expected.unitName);const article=page.locator('#x-lib-grid article').filter({has:page.getByRole('heading',{name:expected.unitName,exact:true})});await article.waitFor();await click(article.getByRole('button',{name:'🔥 Chiến bài này',exact:true}),'start exact pair');await page.locator('#man-b02-play').waitFor();}
 async function fullPass(){assert.equal(await page.locator('#man-b02-answer').count(),0,'Answer before listening');await click(page.locator('#man-b02-play'),'full first pass');await page.locator('#man-b02-submit').waitFor({timeout:200000});const e=await page.evaluate(()=>ManBatch02Practice.evidence());assert.equal(e.fullEnded,true);assert.equal(e.realizationId,expected.audioRealizationRef);for(const item of expected.fullPanelAudio?[{audio:expected.fullPanelAudio,segmentId:'FULL_PANEL'}]:expected.items){const play=e.events.find(x=>x.kind==='FIXED_ASSET_PLAY'&&x.segmentId===item.segmentId);assert.equal(play.sha256,item.audio.sha256);assert.ok(e.events.some(x=>x.kind==='PLAYBACK_ENDED'&&x.segmentId===item.segmentId));}return e;}
 await start();const first=await fullPass();evidence.naturalFullPlayback='ALL_SEGMENTS_ENDED_EXACT_HASH_BOUND';evidence.firstPassEvents=first.events;
 const actual=await page.locator('#man-fixed-audio-player').evaluate(a=>({url:a.currentSrc,duration:a.duration,ended:a.ended,error:a.error?.code||null,dataset:{...a.dataset}}));assert.equal(actual.error,null);assert.equal(actual.ended,true);assert.equal(actual.dataset.assetSha256,(expected.fullPanelAudio||expected.items.at(-1).audio).sha256);evidence.lastPlayback=actual;
 await page.screenshot({path:new URL('learning.png',out).pathname,fullPage:true});
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('#man-b02-submit').waitFor();evidence.resume='PASS_EXACT_REALIZATION_AND_HASHES_RETAINED';
 await click(page.locator('#man-b02-replay-S001'),'assisted replay');await page.waitForFunction(()=>{const a=document.querySelector('#man-fixed-audio-player');return a&&(a.error||a.ended);},null,{timeout:30000});
 await click(page.locator('#man-b02-report-S001'),'audio feedback');evidence.feedbackContext=JSON.parse(await page.locator('#x-audio-report-modal').getAttribute('data-audio-context'));
 assert.equal(evidence.feedbackContext.lessonId,id);assert.equal(evidence.feedbackContext.lessonVersion,'v0.1');assert.equal(evidence.feedbackContext.segmentId,'S001');assert.equal(evidence.feedbackContext.realizationId,expected.audioRealizationRef);assert.equal(evidence.feedbackContext.assetSha256,expected.items[0].audio.sha256);assert.equal(evidence.feedbackContext.deliveryMode,'PERSISTED_ASSET');
 await page.locator('#x-audio-report-category').selectOption({label:'Vấn đề khác'});await page.locator('#x-audio-report-note').fill(`OPERATIONS_${mode.toUpperCase()}_SMOKE_TEST: exact ${id} release verification, not a learner defect.`);
 if(live){await click(page.locator('#x-audio-report-send'),'feedback backend write');await page.locator('#x-audio-report-status').filter({hasText:'Đã gửi.'}).waitFor({timeout:45000});const docId=await page.locator('#x-audio-report-status').getAttribute('data-report-id');assert.ok(docId);evidence.feedbackDocumentIdSha256=createHash('sha256').update(docId).digest('hex');evidence.feedbackWrite='ACKNOWLEDGED_BY_BACKEND';await page.screenshot({path:new URL('feedback.png',out).pathname,fullPage:true});}else evidence.feedbackWrite='NOT_SENT_STAGING';
 await click(page.locator('#x-audio-report-modal').getByRole('button',{name:'Đóng',exact:true}),'close feedback');
 for(const [i,t] of expected.practice.speechTasks.entries())await page.locator('#man-b02-span-'+i).fill(t.answer);
 await page.locator('input[name="b02-answer"][value="0"]').check();await click(page.locator('#man-b02-submit'),'submit inference');await page.locator('#man-b02-result').waitFor();evidence.inference=await page.evaluate(()=>ManBatch02Practice.evidence());assert.equal(evidence.inference.correct,true);assert.equal(evidence.inference.responseAssisted,true);assert.equal(evidence.inference.segmentReplays,1);assert.equal(evidence.inference.accentMastery,undefined);
 const history=await page.evaluate(()=>JSON.parse(localStorage.getItem('man_batch02_evidence_v1')||'[]'));const rows=history.filter(x=>x.lesson_id===id);assert.equal(rows.length,1+expected.practice.speechTasks.length);for(const row of rows){assert.equal(row.realization_id,expected.audioRealizationRef);assert.equal(row.calibrated,false);assert.equal(row.evidence_strength,row.response_format==='SHORT_TEXT'?'REPAIR_ONLY':'WEAK');assert.equal(row.attempt_index,1);assert.ok(row.operator_id);assert.equal(row.audio_realization_ref,expected.audioRealizationRef);assert.equal(row.response_result,'CORRECT');assert.ok(row.target_anchor_id);assert.ok(row.asset_hashes.length);assert.ok(row.correct);}evidence.practiceRows=rows;
 await page.screenshot({path:new URL('completion.png',out).pathname,fullPage:true});await click(page.locator('#man-b02-dictation'),'separate dictation');
 for(let i=0;i<expected.items.length;i++){await page.locator('#progress-tag').filter({hasText:`Câu ${i+1}/${expected.items.length}`}).waitFor();await page.locator('#user-input').fill(expected.items[i].en);}
 await page.locator('#summary-section').getByRole('heading',{name:'Bạn vừa làm được gì?',exact:true}).waitFor({timeout:45000});assert.ok(await page.getByText(`Tự làm đúng ${expected.items.length}/${expected.items.length} câu.`,{exact:false}).isVisible());evidence.dictationCompletion=`${expected.items.length}_OF_${expected.items.length}_SEPARATE_FROM_INFERENCE`;
 await start();await fullPass();for(const [i,t] of expected.practice.speechTasks.entries())await page.locator('#man-b02-span-'+i).fill('incorrect');await page.locator('input[name="b02-answer"][value="1"]').check();await click(page.locator('#man-b02-submit'),'incorrect inference');const negative=await page.evaluate(()=>ManBatch02Practice.evidence());assert.equal(negative.correct,false);assert.equal(negative.responseAssisted,false);assert.ok(negative.evidence.every(x=>!x.correct&&x.exposure_class==='REPAIR'&&x.evidence_strength==='REPAIR_ONLY'&&x.attempt_index===2));evidence.negativeInference='INCORRECT_FIRST_PASS_NOT_SUCCESS';
 evidence.pageErrors=errors;evidence.webSpeechRequests=await page.evaluate(()=>window.manVerificationWebSpeech);assert.deepEqual(errors,[]);assert.equal(evidence.webSpeechRequests,0,'Silent voice substitution');
 await context.route('**/assets/official-lessons-batch02.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...catalog,lessons:catalog.lessons.filter(x=>x.id!==id)})}));
 await page.reload({waitUntil:'domcontentloaded'});await click(page.getByRole('button',{name:'Kho bài học',exact:true}).filter({visible:true}),'rollback nav');await page.locator('article').filter({hasText:'MAN-0065'}).first().waitFor();assert.equal(await page.locator('article').filter({hasText:expected.unitName}).count(),0);assert.equal(await page.locator('#man-b02-panel').count(),0);assert.equal(await page.evaluate(()=>sessionStorage.getItem('man_batch02_practice_v1')),null);evidence.rollback='SCOPED_WITHDRAWAL_NO_CACHED_REVIVAL_PRIOR_LESSONS_RETAINED';
 await context.unroute('**/assets/official-lessons-batch02.json');await page.reload({waitUntil:'domcontentloaded'});await start();evidence.rollbackRestore='EXACT_PAIR_AVAILABLE_AFTER_CATALOG_RESTORE';evidence.status='PASS';evidence.practiceAnchors=expected.practice.anchorIds;
}catch(e){evidence.status='FAIL';evidence.failure=String(e.stack||e);await page?.screenshot({path:new URL('failure.png',out).pathname,fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{evidence.finishedAt=new Date().toISOString();await writeFile(new URL('evidence.json',out),JSON.stringify(evidence,null,2));console.log(JSON.stringify({status:evidence.status,id,mode,target:evidence.target,failure:evidence.failure}));await browser?.close();server?.close();}
